blog/urls.py
from django.urls import path

from .views import post_list, post_detail, post_share, post_comment, search_post
from .feeds import LatestPostFeed


app_name = 'blog'


urlpatterns = [
    # post views
    path("", post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", post_detail, name='post_detail'),
    path("<int:post_id>/share/", post_share, name='post_share'),
    path("<int:post_id>/comment/", post_comment, name='post_comment'),
    path("feed/", LatestPostFeed(), name='post_feed'),
    path("search/", search_post, name='search'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('content.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

from core.models import BaseModel

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                    .filter(status=Post.Status.PUBLISHED)

class Post(BaseModel):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField(max_length=255,
                            unique_for_date="published_at",
                            verbose_name="Slug")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts',
                               verbose_name="Author")
    body = models.TextField(verbose_name="Body")
    published_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT,
                              verbose_name="Status")

    objects = models.Manager()
    published = PublishedManager()

    # Tags Manager
    tags = TaggableManager()

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-published_at']
        indexes = [
            models.Index(fields=['-published_at'])
        ]

    def __str__(self):
        return f"{self.title} by {self.author or ''}"

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.published_at.year,
                             self.published_at.month,
                             self.published_at.day,
                             self.slug
                           ])

class Comment(BaseModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name="comments",
                             verbose_name="Post"
    )
    name = models.CharField(max_length=80, verbose_name="Name")
    email = models.EmailField(verbose_name="E-mail")
    body = models.TextField(verbose_name="Body")
    active = models.BooleanField(default=True, verbose_name="Active?")

    class Meta:
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.views.decorators.http import require_POST
# from django.views.generic import ListView

from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm

# Create your views here.

# class PostListView(ListView):
#     """
#         This is an alternative to the function based view
#     """
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'



def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                   'tag': tag
                  }
    )

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             published_at__year=year,
                             published_at__month=month,
                             published_at__day=day,
                             status=Post.Status.PUBLISHED
    )

    comments = post.comments.filter(active=True).order_by('-created_at')
    form = CommentForm()

    # Retreiving similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-published_at')[:3]

    return render(request,
                  'blog/post/detail.html',
                  {"post":post,
                   "comments": comments,
                   "form": form,
                   "similar_posts": similar_posts
                  }
    )

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post}"
            message = f"Read {post} at {post_url}\n\n {cd['name']}'s comment: {cd['comment']}"
            send_mail(subject, message, "your_account@gmail.com", [cd['to']])
            sent = True

    else:
         form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent}
    )

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request,
                  'blog/post/detail.html#comment_parial',
                  {'post': post,
                   'form': form,
                   'comment': comment
                  }
    )


def search_post(request):
    search_term = request.POST.get('search')
    if len(search_term) == 0:
        posts = Post.published.none()
    else:
        posts = Post.published.filter(body__contains=search_term)
    return render(
        request,
        'blog/base.html#search_result',
        {'search_posts': posts}
    )

templates/blog/base.html
{% load blog_tags %}
{% load partials %}
{% load static %}

<!-- Load template_partials -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link href='{% static "blog/css/base/styles.css" %}' type="text/css" rel="stylesheet">
        <script src="{% static 'htmx/htmx.min.js' %}" defer></script>
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

        <header>
            <h1>My blog</h1>
        </header>

        <div class="container">
            <main id="content">
                {% block content %}
                {% endblock %}
            </main>

        <aside id="sidebar">
                <h2>My blog</h2>
                <p>
                    This is my blog.
                    There are currently {% total_posts %} on this blog.
                </p>

                <div class="search">
                    <div class="search-bar">
                        <input class="search-bar"
                           type="search"
                           name="search"
                           autocomplete="off"
                           placeholder="Begin Typing To Search..."
                           hx-post="{% url 'blog:search' %}"
                           hx-trigger="input changed delay:1s, search"
                           hx-target="#search-results"
                           hx-indicator=".htmx-indicator">
                    </div>

                    <div id="search-results">
                        <!-- Results will be displayed here -->
                        {% partialdef search_result inline=True %}
                            {% for post in search_posts %}
                                <ul>
                                    <li>
                                        <a href="{{ post.get_absolute_url }}">{{post}}</a>
                                    </li>
                                </ul>
                                {% empty %}
                            {% endfor %}
                        {% endpartialdef %}
                    </div>

                    <div class="htmx-indicator">
                        Loading...
                    </div>
                </div>

                 <div class="feed">
                    <p>
                        <a href="{% url "blog:post_feed" %}">
                        Subscribe to my RSS feed
                        </a>
                    </p>
                </div>

                <div class="latest-posts">
                    <h3>Latest posts</h3>
                    {% latest_posts 3 %}
                </div>

                <div class="most-commented">
                    <h3>Most commented</h3>
                    {% most_commented_posts as commented_posts %}
                    <ul>
                        {% for post in commented_posts %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>


        </aside>
        </div>
    </body>
</html>