blog/urls.py
from django.urls import path

from .views import post_list, post_detail, post_share, post_comment, search_post
from .feeds import LatestPostFeed


app_name = 'blog'


urlpatterns = [
    # post views
    path("", post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", post_detail, name='post_detail'),
    path("<int:post_id>/share/", post_share, name='post_share'),
    path("<int:post_id>/comment/", post_comment, name='post_comment'),
    path("feed/", LatestPostFeed(), name='post_feed'),
    path("search/", search_post, name='search'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('content.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

from core.models import BaseModel

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                    .filter(status=Post.Status.PUBLISHED)

class Post(BaseModel):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField(max_length=255,
                            unique_for_date="published_at",
                            verbose_name="Slug")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts',
                               verbose_name="Author")
    body = models.TextField(verbose_name="Body")
    published_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT,
                              verbose_name="Status")

    objects = models.Manager()
    published = PublishedManager()

    # Tags Manager
    tags = TaggableManager()

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-published_at']
        indexes = [
            models.Index(fields=['-published_at'])
        ]

    def __str__(self):
        return f"{self.title} by {self.author or ''}"

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.published_at.year,
                             self.published_at.month,
                             self.published_at.day,
                             self.slug
                           ])

class Comment(BaseModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name="comments",
                             verbose_name="Post"
    )
    name = models.CharField(max_length=80, verbose_name="Name")
    email = models.EmailField(verbose_name="E-mail")
    body = models.TextField(verbose_name="Body")
    active = models.BooleanField(default=True, verbose_name="Active?")

    class Meta:
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.views.decorators.http import require_POST
# from django.views.generic import ListView

from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm

# Create your views here.

# class PostListView(ListView):
#     """
#         This is an alternative to the function based view
#     """
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'



def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                   'tag': tag
                  }
    )

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             published_at__year=year,
                             published_at__month=month,
                             published_at__day=day,
                             status=Post.Status.PUBLISHED
    )

    comments = post.comments.filter(active=True).order_by('-created_at')
    form = CommentForm()

    # Retreiving similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-published_at')[:3]

    return render(request,
                  'blog/post/detail.html',
                  {"post":post,
                   "comments": comments,
                   "form": form,
                   "similar_posts": similar_posts
                  }
    )

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post}"
            message = f"Read {post} at {post_url}\n\n {cd['name']}'s comment: {cd['comment']}"
            send_mail(subject, message, "your_account@gmail.com", [cd['to']])
            sent = True

    else:
         form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent}
    )

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request,
                  'blog/post/detail.html#comment_parial',
                  {'post': post,
                   'form': form,
                   'comment': comment
                  }
    )


def search_post(request):
    search_term = request.POST.get('search')
    if len(search_term) == 0:
        posts = Post.published.none()
    else:
        posts = Post.published.filter(body__contains=search_term)
    return render(
        request,
        'blog/base.html#search_result',
        {'search_posts': posts}
    )

templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post</a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

<script>
    document.getElementById('post-comments').addEventListener('htmx:afterSwap', function(event) {
        var commentDivs = document.querySelectorAll('#post-comments .comment');
        commentDivs.forEach(function(commentDiv, index) {
            commentDiv.dataset.commentIndex = index + 1; // Update the comment index
        });
    });
</script>

<!-- Load template_partials -->
{% load partials %}

{% block title %} {{ post }} {% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        published at {{ post.published_at }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post }}</a>
        </p>
        {% empty %}
            There are no similar posts yet!
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    <div id="post-comments">
        {% for comment in comments %}
            {% partialdef comment_parial inline=True %}
            <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created_at }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
            {% endpartialdef %}
            {% empty %}
            <p>There are no comments.</p>
        {% endfor %}
    </div>
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post }}
            </a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My published blogs{% endblock %}

{% block content %}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="post-item">
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="tags">
                Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">
                Published {{ post.published_at }} by {{ post.author }}
            </p>
        {{ post.body|truncatewords:30|markdown }}
        </div>
    {% endfor %}
    {% include "generics/pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail sent successfully</h1>
        <p>
            "{{ post }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>share "{{ post }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}