blog/urls.py
from django.urls import path

from .views import post_list, post_detail, post_share, post_comment, search_post
from .feeds import LatestPostFeed


app_name = 'blog'


urlpatterns = [
    # post views
    path("", post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", post_detail, name='post_detail'),
    path("<int:post_id>/share/", post_share, name='post_share'),
    path("<int:post_id>/comment/", post_comment, name='post_comment'),
    path("feed/", LatestPostFeed(), name='post_feed'),
    path("search/", search_post, name='search'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('content.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
]

templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form
    hx-post="{% url 'blog:post_comment' post.id %}"
    hx-target="#post-comments"
    hx-swap="beforeend"
    hx-on::after-request="this.reset()">
    {{ form.as_p }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Add comment">
    </p>
</form>